[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:main-server]
command=java -jar /app/main-server.jar --server.port=8080
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:user-microservice]
command=java -jar /app/user-microservice.jar --server.port=8081
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:device-microservice]
command=java -jar /app/device-microservice.jar --server.port=8082
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:messaging-microservice]
command=java -jar /app/messaging-microservice.jar --server.port=8083
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:social-microservice]
command=java -jar /app/social-microservice.jar --server.port=8084
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0